package batchExp;

public class Fitness {
	// fitness
	public double fitness1; // total cost
	public double fitness2; // completion time
	
	// normalized
	public double norf1;
	public double norf2;
	// generated by which algorithm
	public int from;
	
	public Fitness(double f1, double f2) {
		this.fitness1 = f1;
		this.fitness2 = f2;
	}
	
	public Fitness(double f1, double f2, int from) {
		this.fitness1 = f1;
		this.fitness2 = f2;
		this.from = from;
	}
	
	public String stringHash() {
		return norf1 + "," + norf2;
	}
}
